### ISSUE TITLE
Show more than 20 pics

### ISSUE THREAD

**Issue by julienchazal** [potomak/jquery-instagram#12]
Hello
Thx for your plugin !
I tried your alternative method to show more than 20 photos, but i get this error message :

Uncaught TypeError: Cannot read property 'pagination' of undefined 

any idea please ?

thx !

**Comment by julienchazal** [comment]
Any ideas please ?
Here's the link : http://www.eurowcable2012.com/pics2.html

thx

**Comment by potomak** [comment]
You're using an outdated version of the plugin.

**Comment by julienchazal** [comment]
sorry ;-)
thanks !!!
