### ISSUE TITLE
Set show to 20 and it shows 14

### ISSUE THREAD

**Issue by ghost** [potomak/jquery-instagram#14]
I have set the show to 20 and it only shows 14. Set it to show 2 and it only shows 1.

my version of your plugin. http://pastebin.com/iX4vjheA

**Comment by potomak** [comment]
Please create a new fiddle at http://jsfiddle.net/ with your code linking the latest jquery-instagram library.

**Comment by ghost** [comment]
The best way would be to link you to what I'm working on as I have edited the jquery-instagram file 

http://flatterd.cleanly.co/

http://flatterd.cleanly.co/assets/js/instagram.js

**Comment by potomak** [comment]
Please post a fiddle to let me test your code in a _controlled environment_, I'm here to help about jquery-instagram, not about the whole app.

**Comment by guirogieri** [comment]
I have the same problem. Not showing all photos tagged. Have an issue on instagram.js file?!

**Comment by potomak** [comment]
Here's my test: http://jsfiddle.net/tzxE5/

**Comment by ghost** [comment]
From what I managed to get on console.log a few times. The
script/plugin sometimes doesn't pass through the data along with the
image. 

On 2012-10-17 16:33, Giovanni Cappellotto wrote: 

> Here's my
> test: http://jsfiddle.net/tzxE5/ [1] 
> 
> ## 
> 
> Reply to this email
> directly or view it on GitHub [2].

## Links:

[1]
http://jsfiddle.net/tzxE5/
[2]
https://github.com/potomak/jquery-instagram/issues/14#issuecomment-9531766

**Comment by guirogieri** [comment]
sometimes, this ocurrs because some users use private photos.

**Comment by ghost** [comment]
That'll explain it, is there a way to exclude such images? 

On
2012-10-17 16:44, guirogieri wrote: 

> sometimes, this ocurrs because
> some users use private photos. 
> 
> ## 
> 
> Reply to this email directly
> or view it on GitHub [1].

## Links:

[1]
https://github.com/potomak/jquery-instagram/issues/14#issuecomment-9532216

**Comment by guirogieri** [comment]
I dont know. But try this in your ajax request.

``` javascript
if(res.data.length <  settings.show) {
    total = settings.show - res.data.length;
    next_url = res.pagination.next_url;
    functionTest(total, next_url);
}
```

And create this function to call the rest of images.

``` javascript
function functionTest(total, url)  {
    console.log("callback: "+url);
    $(".content").instagram({
        next_url : url, 
        show : total, 
        onComplete : function(photos, data) {
            testeGlobal = data.pagination.next_url
        }
    });
}
```

**Comment by potomak** [comment]
@guirogieri is right, thanks for pointing it out and see also https://groups.google.com/d/msg/instagram-api-developers/nKik4i8OYhw/l0HxXHvpnIAJ
