### ISSUE TITLE
Merging w/ DamianMullins / jquery-instagram

### ISSUE THREAD

**Issue by adaptive** [potomak/jquery-instagram#15]
Request to pull the: Added setting to specify image size on  DamianMullins / jquery-instagram

**Comment by potomak** [comment]
Please @DamianMullins create a new pull request with requested feature.

**Comment by potomak** [comment]
Closed by #16

**Comment by petripottonen** [comment]
Hi there!
What happened here, I don't see the option for image sizes on the newest commit? I only see it on  @DamianMullins fork which is a lot older?

**Comment by potomak** [comment]
@ketri the plugin doesn't generate anymore HTML code for you so you don't need to specify image size. See an example usage at http://potomak.github.io/jquery-instagram/

**Comment by petripottonen** [comment]
@potomak Thanks very much for your reply.
Unfortunately still don't quite understand how to proceed if I want to use larger images than 150px*150px that example gives out. 
Is there a way to make the plugin get larger versions of the images?

Thanks!

**Comment by petripottonen** [comment]
Ahh, now I got it. I just change. 
.attr('src', photo.images.thumbnail.url); 
to 
.attr('src', photo.images.standard_resolution.url);
or
.attr('src', photo.images.low_resolution.url);

I found this info from another issue, is this available on the readme or somewhere for new users?
