### ISSUE TITLE
Request: Display photos from 'userId' tagged 'hash'

### ISSUE THREAD

**Issue by bradcerasani** [potomak/jquery-instagram#23]
These two functions are available independently, any possible way to combine them? 

I don't think the Instagram API readily supports this, but perhaps it's possible to fetch all images from a specific user and then filter those images by hashtag?

**Comment by potomak** [comment]
As you notice this isn't an Instagram API function (see http://instagram.com/developer/endpoints/users/#get_users_media_recent) so I think this shouldn't be implemented as a library function.
