### ISSUE TITLE
Returning photos with https instead of http

### ISSUE THREAD

**Issue by bodrovis** [potomak/jquery-instagram#25]
Hello.

By default photos returned by Instagram use http, like "http://distilleryimage5.s3.amazonaws.com/some_photo.jpg". Is there any way to instruct Instagram API to return photos using https, not http?

**Comment by moiseevigor** [comment]
The workaround is to simply substitute "http" by "https". 
Should work "https://distilleryimage5.s3.amazonaws.com/some_photo.jpg"

**Comment by bodrovis** [comment]
Well, yes, but i thought that there may be some special parameter for it (for lazy programmers :)). For example, Facebook provides an option called return_ssl_resources, like this: "https://graph.facebook.com/username/picture?return_ssl_resources=1"

**Comment by moiseevigor** [comment]
As far as I know Instagram does not provide this functional and so nor jquery-instagram, which looks to me correct. Let's wait for potomak confirmation of this.

**Comment by potomak** [comment]
@moiseevigor is right, there's not such option, see http://instagram.com/developer/endpoints/media/
