### ISSUE TITLE
getting a 404 error coming back through

### ISSUE THREAD

**Issue by jrdn91** [potomak/jquery-instagram#28]
Looks like this

https://api.instagram.com/v1/tags/?callback=jQuery1830384592188289389_1362287165365&_=1362287165377

It says the server didn't find anything there, not sure if they recently updated their url structure or something but I'm not getting anything back. I made sure my userId and secret are there.

**Comment by potomak** [comment]
You should add a tag: https://api.instagram.com/v1/tags/test

**Comment by jrdn91** [comment]
Is there a way to do it without a hashtag?
