### ISSUE TITLE
Show numbers of likes and comments under images.

### ISSUE THREAD

**Issue by salle81** [potomak/jquery-instagram#29]
Hey.

Thanks for your great work. I have tried to show the likes and comments under the images without any good results. I have looked at this site. http://www.transparentspeaker.com/ and really liked there solution but haven get it to work by my own.

Do you have any tips how i can get this to work?

---- i solved it---

Best regards Henrik

**Comment by betron** [comment]
Hey Henrik, 

I may want to do this as well (if I can ever get this code to work and get an image displayed). Could you share how you pulled it off? Thanks.

**Comment by salle81** [comment]
Hey!  

Check this user on git. This works perfect.

https://github.com/PhilipKnape/app

/ Henrik   

---

Henrik Samuelsson
Mobil: +46 720 07 99 14
Mail: salle81@gmail.com

**Comment by betron** [comment]
I can't find the live site for this code, I wanted to see how it looks on the page. Also, how do I get an accessToken from Instagram? I think I need this in order to use the userId and get the most recent photo from the account.

**Comment by potomak** [comment]
@betron you can see preview of any HTML file on GitHub using http://htmlpreview.github.com/?https://github.com/PhilipKnape/app/blob/master/index.html

Anyway, modify plugin's internals to show custom data is the wrong way to achieve this feature. This is the reason I'm working on a new version of the scripts that runs only the `onComplete` callback if provided, see #21.

/cc @PhilipKnape @salle81
