### ISSUE TITLE
Overwriting PhotoLink and other settings

### ISSUE THREAD

**Issue by brettalton** [potomak/jquery-instagram#33]
I think there should be the ability to build your own anchor if you'd like and be able to overwrite the settings. So instead of using

``` javascript
settings = {
  // ...
  , photoLink: true
};
```

You allow for the ability to override or not. Current it just says,

``` javascript
if (settings.photoLink) {
  innerHtml = $('<a>')
    .attr('target', '_blank')
    .attr('href', photo.link)
    .append(innerHtml);
}
```

which only allows for bool.

And now that I have this script on CDNjs (http://cdnjs.com), vanilla copies may be preferred, rather than custom hacks to source code.

**Comment by potomak** [comment]
I agree, but I'd like to let customize HTML code generation by overriding the `onComplete` callback, see #21.

**Comment by ghost** [comment]
is there currently anyway to override the HTML as proposed above? I would like to enlarge images using a lightbox versus bringing the user to the instagram site.

**Comment by potomak** [comment]
Since version [0.3.0](https://github.com/potomak/jquery-instagram/releases/tag/0.3.0) plugin doesn't generate code anymore, see also documentation for the `didLoadInstagram` event: https://github.com/potomak/jquery-instagram#didloadinstagram
