### ISSUE TITLE
Callback

### ISSUE THREAD

**Issue by brettalton** [potomak/jquery-instagram#34]
Adding a callback to know when the plugin completes would be useful too.

http://stackoverflow.com/questions/2534436/jquery-plugin-adding-callback-functionality

Thoughts?

**Comment by potomak** [comment]
I think it's more useful to get triggered when call to Instagram API ends, see #30, but also this event (plugin execution end) could be triggered.

**Comment by potomak** [comment]
Since version [0.3.0](https://github.com/potomak/jquery-instagram/releases/tag/0.3.0) plugin triggers a `didLoadInstagram` event, see https://github.com/potomak/jquery-instagram#didloadinstagram
