### ISSUE TITLE
getting "object has no method 'instagram' " error.

### ISSUE THREAD

**Issue by cjch0** [potomak/jquery-instagram#39]
i already saw this post: https://github.com/potomak/jquery-instagram/issues/4
but the solution does not apply in my case.

$(".instagram").instagram({
    hash: 'something',
    clientId: myClientId
});

I've imported the script and followed all instructions, but still nothing. please help!

**Comment by potomak** [comment]
create a fiddle or post your code here to get support please

**Comment by cjch0** [comment]
http://jsfiddle.net/ZqHhs/4/

here is my fiddle. I loaded the same external resource uri that you used in
your fiddles.

**Comment by potomak** [comment]
New versions of Chrome browser don't allow javascript resources with the wrong MIME type.

See the error:

```
Refused to execute script from 'https://raw.github.com/potomak/jquery-instagram/master/jquery.instagram.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
```

Example solution: use http://cdnjs.cloudflare.com/ajax/libs/jquery-instagram/0.2.2/jquery.instagram.js (http://jsfiddle.net/ZqHhs/5/)

See also #38
