### ISSUE TITLE
no method 'instagram'

### ISSUE THREAD

**Issue by TonyNg** [potomak/jquery-instagram#4]
I'm getting a no method 'instagram' from following the sample provided in the Readme.  Any suggestions?

 `$(".instagram").instagram({`

**Comment by potomak** [comment]
Did you import plugin script?

``` html
<script src="jquery.instagram.js"></script>
```

**Comment by TonyNg** [comment]
Okay, turns out that I used the source from your page instead of grabbing the most recent version on Github.

It works now that I'm using the updated code.
