### ISSUE TITLE
Change default distance using lat/long search?

### ISSUE THREAD

**Issue by michaelgiaimo** [potomak/jquery-instagram#40]
According to the API specs:

Default is 1000m (distance=1000), max distance is 5000.

Do we have control over it in this script?  Would love to reduce it for greater accuracy.  I see  in line 87:

```
settings.search.distance != null && (params.distance = settings.search.distance);
```

**Comment by potomak** [comment]
@velcrobots you're right, you can set the `distance` parameter adding a distance attribute to the `search` object.
If you want to update documentation I'd be glad to merge such pull request.

**Comment by michaelgiaimo** [comment]
Awesome, will do.  Does this mean we can also pass the 'FOURSQUARE_V2_ID' or 'FOURSQUARE_ID'?

**Comment by potomak** [comment]
Well, no (see https://github.com/potomak/jquery-instagram/blob/master/jquery.instagram.js#L81-88), but you can add those search parameters and make a pull request.

**Comment by ghost** [comment]
Do you mind adding this to the documentation? BY this, I mean setting the distance parameter by adding a distance attribute to the search object. Thanks!

**Comment by michaelgiaimo** [comment]
I'd love to - I've actually never contributed to a project on GitHub
though.  Do I just clone it, edit the ReadMe, then commit?

**Comment by potomak** [comment]
It's even easier:
1. open https://github.com/potomak/jquery-instagram/blob/master/README.md
2. click "Edit"
3. send the pull request
