### ISSUE TITLE
Likes Limits

### ISSUE THREAD

**Issue by matteobelfiore** [potomak/jquery-instagram#42]
Hello, 

does anyone know why I get a correct likes count for a photo, let's say 11 for example, and then in the following array containing the likes I only have 3 or 4 cells, and not all the 11 likes?

It happens with all the photos I try to retrieve.

Thanks for your help.

Matt

**Comment by potomak** [comment]
@heartbox lists of photos contain only a subset of likers (see example response at http://instagram.com/developer/endpoints/media/#get_media_popular), if you need to retrieve them all you must make a call to http://instagram.com/developer/endpoints/media/#get_media

**Comment by matteobelfiore** [comment]
Yeah the problem is that I'm retrieving them per tag and not per media id or popularity. How do I solve this in my situation? Thanks for your help

**Comment by potomak** [comment]
You should request each media individually to retrieve the whole list of likers.
