### ISSUE TITLE
instagramjs-rails gem is available for Rails developers

### ISSUE THREAD

**Issue by bodrovis** [potomak/jquery-instagram#44]
Hello. I have created a gem (library) to allow Rails developers easily include Instagram.js to their projects. It can be installed by calling `gem install "instagramjs-rails"`. More detailed information can be found here https://github.com/bodrovis/instagramjs-rails. So you can mention this gem in the Readme file.

**Comment by potomak** [comment]
If you want to make a PR mentioning the gem in the README I'll merge it.
