### ISSUE TITLE
v0.2.1 Now producing "no photos for this query"

### ISSUE THREAD

**Issue by jet2k** [potomak/jquery-instagram#48]
Client ID etc are all correct. Nothing changed. Simply stopped working one day? :(

**Comment by potomak** [comment]
Please provide more debug info about this issue or just update to version 0.3.

**Comment by jet2k** [comment]
Thank you for responding and for the cool script! Hopefully this helps

jQuery19107822789635579199_1389455812110({"meta":{"error_type":"OAuthAccessTokenException","code":400,"error_message":"The access_token provided is invalid."}})

the code:
http://pastebin.com/ueKBYsyf

**Comment by potomak** [comment]
Simply `The access_token provided is invalid`. Try a new client id.

Closing as it's not a jQuery Instagram issue.
