### ISSUE TITLE
What is the limit for number of images? Is it possible to overcome it or implement infinite scroll?

### ISSUE THREAD

**Issue by petripottonen** [potomak/jquery-instagram#53]
Hello

It seems that there is a limit where I cannot load more images. I read another issue here where it said that since some instagram-photos are private, it won't always output as many images as specified. But even if I put something like 1000, there seems to be a limit besides that.

Is it possible to make another requst to load more images and this way create infinite scroll type behaviour?

Thank you!

**Comment by petripottonen** [comment]
Ok, it might have been a "bug", since there may not be enough images on the area I was searching.

**Comment by potomak** [comment]
Please see https://github.com/potomak/jquery-instagram#count
