### ISSUE TITLE
Hide accesstoken and userID

### ISSUE THREAD

**Issue by mathetos** [potomak/jquery-instagram#54]
Do you have a suggestion for hiding the accesstoken and userID from being output onto the page when using this? I don't think users would really like that info to be naked in their site code. Do you have examples of this being used publicly. I noticed the demo only uses the clientID which is fine because you can limit your Client by domain, but not so when pulling info from a personal account.

Any suggestions or examples would be appreciated. Thanks for putting this together, great work overall!

**Comment by potomak** [comment]
Does #5 answer your question?
If you have more questions please put them on StackOverflow.
