### ISSUE TITLE
Thumbnail Size

### ISSUE THREAD

**Issue by joshuwack** [potomak/jquery-instagram#7]
Is there a way to control the size of the thumbnail?

**Comment by potomak** [comment]
Instagram API returns a list of images with the format:

```
"images": {
  "low_resolution": {
    "url": "http://distillery.s3.amazonaws.com/media/2010/07/16/4de37e03aa4b4372843a7eb33fa41cad_6.jpg",
    "width": 306,
    "height": 306
  },
  "thumbnail": {
    "url": "http://distillery.s3.amazonaws.com/media/2010/07/16/4de37e03aa4b4372843a7eb33fa41cad_5.jpg",
    "width": 150,
    "height": 150
  },
  "standard_resolution": {
    "url": "http://distillery.s3.amazonaws.com/media/2010/07/16/4de37e03aa4b4372843a7eb33fa41cad_7.jpg",
    "width": 612,
    "height": 612
  }
}
```

See examples at http://instagram.com/developer/endpoints/media/

By default jquery-instagram uses `createPhotoElement` function to create image elements which takes thumbnail image URL and put it inside the `src` attribute of `img` element (see https://github.com/potomak/jquery-instagram/blob/master/jquery.instagram.js#L33).

You can override this by setting `onComplete` option with a function which takes two parameters:
1. `data`<br>partial response data with images
2. `response`<br>an object containing response from Instagram API

(see also https://github.com/potomak/jquery-instagram/blob/master/jquery.instagram.js#L105)
