### ISSUE TITLE
Just says 'No photos for this query'?

### ISSUE THREAD

**Issue by cmykaye** [potomak/jquery-instagram#8]
No matter what tag I use, nothing works?

Here's the .js file:

http://yyy.comuf.com/jquery.instagram.js

And the script:

$(function() {
  $(".instagram").instagram({
      hash: 'op'
    , clientId: '17329093'
  });
});

**Comment by cmykaye** [comment]
I'm practicing with this file but same thing happens. I have a feeling it's a really stupid solution. :/

http://yyy.comuf.com/instagram.php

**Comment by potomak** [comment]
It is, you're using a wrong `clientId`. If you're using Google Chrome you can look at Inspector's "Network" tab and see this response form Instagram API:

```
{
    "meta": {
        "error_type": "OAuthClientException",
        "code": 400,
        "error_message": "The \"client_id\" provided is invalid and does not match a valid application."
    }
}
```

**Comment by cmykaye** [comment]
How do I get the correct client ID?

**Comment by potomak** [comment]
Go to http://instagr.am/developer/register/ and register a new client app then Flattr jquery-instagram at http://flattr.com/thing/269500/Instagram-jQuery-plugin :)
