### ISSUE TITLE
Alternative method-Problem

### ISSUE THREAD

**Issue by ghost** [potomak/jquery-instagram#9]
Hello! I am having problems with the alternative method.

Here is a working example on Fiddle.

http://jsfiddle.net/harisn/2DuGb/2/

The problem is when i run it on my server it doesn't work :s

http://demo.harisninios.com/

What i am doing wrong ?

**Comment by potomak** [comment]
Hi,
you're not including jQuery.

Before posting any issue please double check javascript console for errors, you would have noticed the `Uncaught ReferenceError: jQuery is not defined` message.
